trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  PSGalleryApiKey: $(PSGalleryApiKey)

steps:
- task: PowerShell@2
  displayName: 'Install Pester and NuGet Provider'
  inputs:
    targetType: 'inline'
    script: |
      if (-not (Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue)) {
        Write-Host "Installing NuGet package provider..."
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Install-PackageProvider -Name NuGet -Force
      }

      if (-not (Get-Module -ListAvailable -Name Pester) -or ((Get-Module -ListAvailable -Name Pester).Version.Major -lt 5)) {
        Write-Host "Installing Pester 5..."
        Install-Module Pester -Force -Scope CurrentUser -MinimumVersion 5.0.0
      }

      Import-Module Pester -Force


- task: PowerShell@2
  displayName: 'Run Unit Tests'
  inputs:
    targetType: 'inline'
    script: |
      Invoke-Pester -Script './StorageAccountBlobHelper.Tests.ps1' -Output Detailed

- task: PowerShell@2
  displayName: 'Publish to PowerShell Gallery'
  condition: succeeded()
  inputs:
    targetType: 'inline'
    script: |
      Publish-Module -Path './StorageAccountBlobHelper' -NuGetApiKey $env:PSGalleryApiKey
