name: Python Storage Account Blob Helper PR Validation
# This workflow validates pull requests for the Python Storage Account Blob Helper project.

on:
  pull_request:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust if needed
      - name: Show current path
        run: |
          echo "Current directory:"
          pwd
          echo "Directory listing:"
          ls -la
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Python/StorageAccountBlobHelper/requirements.txt
          pip install .

      - name: Run tests
        run: |
          python -m unittest discover -s . -p "*Tests.py"
