name: Python Storage Account Blob Helper PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'      

      - name: Install dependencies
        working-directory: Python/StorageAccountBlobHelper
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Run tests
        working-directory: Python/StorageAccountBlobHelper
        run: |
          python -m unittest discover -s . -p "*Tests.py"
