name: PowerShell Module CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pester and NuGet provider
      shell: pwsh
      run: |
        if (-not (Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue)) {
          Write-Host "Installing NuGet package provider..."
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Install-PackageProvider -Name NuGet -Force
        }

        if (-not (Get-Module -ListAvailable -Name Pester) -or ((Get-Module -ListAvailable -Name Pester).Version.Major -lt 5)) {
          Write-Host "Installing Pester 5..."
          Install-Module Pester -Force -Scope CurrentUser -MinimumVersion 5.0.0
        }

        Import-Module Pester -Force

    - name: Run Unit Tests
      shell: pwsh
      run: |
        Invoke-Pester -Script './AzureHelpers/tests/StorageAccountBlobHelper.Tests.ps1' -Output Detailed -Passthru | Tee-Object -Variable testResults
        if ($testResults.FailedCount -gt 0) {
          Write-Error "One or more Pester tests failed."
          exit 1
        }

    - name: Publish to PowerShell Gallery
      if: success()
      shell: pwsh
      env:
        NUGET_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
      run: |
        Publish-Module -Path './AzureHelpers' -NuGetApiKey $env:NUGET_API_KEY
