name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pester and NuGet provider
      shell: pwsh
      run: |
        if (-not (Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue)) {
          Write-Host "Installing NuGet package provider..."
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Install-PackageProvider -Name NuGet -Force
        }

        if (-not (Get-Module -ListAvailable -Name Pester) -or ((Get-Module -ListAvailable -Name Pester).Version.Major -lt 5)) {
          Write-Host "Installing Pester 5..."
          Install-Module Pester -Force -Scope CurrentUser -MinimumVersion 5.0.0
        }

        Import-Module Pester -Force

    - name: Run Pester Tests
      shell: pwsh
      run: |
        Invoke-Pester -Script './StorageAccountBlobHelper.Tests.ps1' -Output Detailed
